### ISSUE TITLE
Filter Does not show up under Settings even when it is installed 05-24-2018

### ISSUE THREAD

**Issue by tazzarkin** [6ec123321/filters#34]
I have two versions of RoundCube with all the same plugins.  And I just downloaded the newest version of the Filters plug-in (May 24, 2018).

For RoundCube v. 1.2, the Filter plugin works great.

However, for RoundCube v. 1.3, the Filter plugin shows up in the About window as installed, but the Filter option does not show up under Settings.  (See the attached image)

What could be causing this?

![roundcube filters](https://user-images.githubusercontent.com/39584816/40474342-597aa2b0-5f71-11e8-824f-967e77c64a95.png)

**Comment by 6ec123321** [comment]
You are using elastic skin?12:45, 24 мая 2018 г., tazzarkin <notifications@github.com>:I have two versions of RoundCube with all the same plugins. For RoundCube v. 1.2, the Filter plugin works great. However, for RoundCube v. 1.3, the Filter plugin shows up in the About window as installed, but the Filter option does not show up under Settings. (See the attached image) What could be causing this?  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by tazzarkin** [comment]
Actually, I tried different skins.

I think it had something to do with Soap not being installed properly.  After installing soap and enabling it in my php.ini file, then everything started to work properly.

**Comment by tazzarkin** [comment]
Just for your information (for testing), I am using the roundcubeplus.com skins.  (Hence, that's why it says xskin in the About window).

**Comment by 6ec123321** [comment]
try this plug-in https://github.com/6ec123321/chbox. 
fixed for RC1.3

**Comment by 6ec123321** [comment]
Just for your information (for testing).

**Comment by tazzarkin** [comment]
Okay, I will try it out.  

Thank you again for the prompt reply.

(FYI - I also like your rcplugin_password plugin.  Fascinating...)
