### ISSUE TITLE
Filter for Junk Folder

### ISSUE THREAD

**Issue by bralindontez** [6ec123321/filters#40]
Thanks for your efforts! How can I move messages from Junk to Inbox containing specific words in Subject?

**Comment by bralindontez** [comment]
Also does this filter will only work if account is open or it can work in background?

**Comment by 6ec123321** [comment]
1. How can I move messages from Junk to Inbox containing specific words in Subject?
**It is necessary to train an anti-spam filter on the server side so that the letter does not fall into spam.**
2. Also does this filter will only work if account is open or it can work in background?
**Hello. This filter will only work if account is open in browser, because this client-side email filter.**

**Comment by bralindontez** [comment]
Can you please help this script do something that it can also move on the messages from Junk to Inbox as per conditions. I'll really appreciate your help and will obviously pay for that help.

**Comment by 6ec123321** [comment]
I know how to do what you ask. How much will you pay?

**Comment by bralindontez** [comment]
What you are looking for? Is there any email we can communicate on?

**Comment by 6ec123321** [comment]
write to arturolegovich@gmail.com

**Comment by 6ec123321** [comment]
Download and test, please.
