### ISSUE TITLE
Filters are gone after roundcube update

### ISSUE THREAD

**Issue by botkillern** [6ec123321/filters#46]
Hi,

I've one situation where the clients lost your filters after WHM update roundcube packages.
I want to know if it's possible to recovery these filters? Maybe the filters are stored in some file...

I saw in some recent issue that the filters are stored in **Database(Table User and Fild Settings)**, but I can't find it.
I think maybe I can restore a backup before the update in a isolate machine and export the filters to the current running server.

If you don't understand something, just tell, english isn't my native language.

Thank you, Regards!

**Comment by syspir** [comment]
filters have stopped working for me too, they are displayed in the panel, but they do not work.

filters are stored in the users database column preferences

**Comment by 6ec123321** [comment]
HI, gyes, let's start:
1. What version of roundcubemail you are using?
2. Whow are you update plugin's?

Please, answer this two questions, and I start to debug the plugin.

**Comment by 6ec123321** [comment]
And another question, can you make me the test virtual server on linux for debug, small server with 2GB RAM and 1-2 CPUs. My job is System Administration of Windows Systems, *Nix Systems, no matter FreeBSD/Debian/CentOS/etc.

**Comment by 6ec123321** [comment]
Windows or Linux or Unix - all systems are great, I'l take all xD), i'd like all systems, holyware is for stupid IT-managers.

**Comment by syspir** [comment]
version 1.3.9

plugin latest

**Comment by dapphp** [comment]
I have similar reports that existing filters have stopped working after an update. Identical filters matching old ones that were re-created in the new version work, but not the old ones.  At least 5 separate accounts have reported issues with filtering since the upgrade.

Previously running: Roundcube 1.3.8 with dev-filters-2.1.7 (19e8d3a)

Upgraded to: Roundcube 1.3.9 with dev-filters-2.1.9 (4d6822e)

I have rolled back to 2.1.7 (but did not roll back Roundcube) and will report back if the filters begin to work again.

**Comment by dapphp** [comment]
I've only heard back from one person, but they report that all of their original filters are working again after downgrading the plugin to 2.1.7.

**Comment by 6ec123321** [comment]
Try new release https://github.com/6ec123321/filters/releases/tag/filters-2.2.0.
